-- 환자 샘플 데이터 (상태별 골고루)
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('홍길동', '감기', DATEADD('YEAR', -30, CURRENT_DATE), 'WAITING', false, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('김철수', '장염', DATEADD('YEAR', -25, CURRENT_DATE), 'WAITING', false, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('이영희', '고혈압', DATEADD('YEAR', -52, CURRENT_DATE), 'IN_PROGRESS', false, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('박민준', '당뇨', DATEADD('YEAR', -61, CURRENT_DATE), 'IN_PROGRESS', false, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('최수연', '폐렴', DATEADD('YEAR', -45, CURRENT_DATE), 'HOSPITALIZED', false, CURRENT_DATE, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('정우성', '골절', DATEADD('YEAR', -38, CURRENT_DATE), 'HOSPITALIZED', false, CURRENT_DATE, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('한지민', '맹장염', DATEADD('YEAR', -29, CURRENT_DATE), 'COMPLETED', true, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('오세훈', '위염', DATEADD('YEAR', -44, CURRENT_DATE), 'COMPLETED', true, null, null);
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('윤아름', '디스크', DATEADD('YEAR', -55, CURRENT_DATE), 'DISCHARGED', true, DATEADD('DAY', -7, CURRENT_DATE), DATEADD('DAY', -1, CURRENT_DATE));
INSERT INTO PATIENT (NAME, DISEASE, BIRTH_DATE, STATUS, IS_PAID, ADMISSION_DATE, DISCHARGE_DATE) VALUES ('강동원', '심근경색', DATEADD('YEAR', -67, CURRENT_DATE), 'DISCHARGED', true, DATEADD('DAY', -14, CURRENT_DATE), DATEADD('DAY', -3, CURRENT_DATE));

-- 예약 샘플 데이터
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (1, CURRENT_DATE, '09:00', '김의사', '정기 검진', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (2, CURRENT_DATE, '10:30', '이의사', '추적 관찰', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (3, CURRENT_DATE, '11:00', '박의사', '혈압 체크', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (4, DATEADD('DAY', 1, CURRENT_DATE), '09:30', '김의사', '당뇨 관리', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (5, DATEADD('DAY', 1, CURRENT_DATE), '14:00', '이의사', '경과 관찰', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (6, DATEADD('DAY', 2, CURRENT_DATE), '10:00', '박의사', '골절 추적', 'SCHEDULED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (7, DATEADD('DAY', -1, CURRENT_DATE), '10:00', '김의사', '수술 후 점검', 'COMPLETED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (8, DATEADD('DAY', -2, CURRENT_DATE), '15:00', '이의사', '위내시경', 'COMPLETED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (9, DATEADD('DAY', -3, CURRENT_DATE), '13:00', '박의사', '재활 상담', 'CANCELLED');
INSERT INTO APPOINTMENT (PATIENT_ID, APPOINTMENT_DATE, APPOINTMENT_TIME, DOCTOR_NAME, PURPOSE, STATUS) VALUES (1, DATEADD('DAY', 3, CURRENT_DATE), '13:00', '박의사', '재진', 'SCHEDULED');

-- 진료 기록 샘플 데이터
-- 홍길동 (id=1) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('기침, 콧물', '급성 상기도염', '타이레놀, 항히스타민제', CURRENT_DATE, '김의사', 15000, 1);

-- 김철수 (id=2) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('복통, 설사', '급성 장염', '정장제, 수액 처방', CURRENT_DATE, '이의사', 25000, 2);

-- 이영희 (id=3) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('두통, 어지럼증', '본태성 고혈압', '아ムロ디핀 5mg', DATEADD('DAY', -30, CURRENT_DATE), '박의사', 18000, 3);
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('혈압 상승', '고혈압 악화', '약 용량 증가', CURRENT_DATE, '박의사', 18000, 3);

-- 박민준 (id=4) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('혈당 상승, 피로감', '2형 당뇨', '메트포르민 500mg', DATEADD('DAY', -60, CURRENT_DATE), '김의사', 22000, 4);
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('혈당 조절 불량', '당뇨 합병증 주의', '인슐린 추가', CURRENT_DATE, '김의사', 35000, 4);

-- 최수연 (id=5) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('고열, 기침, 호흡곤란', '세균성 폐렴', '항생제 정맥 투여', DATEADD('DAY', -3, CURRENT_DATE), '이의사', 85000, 5);

-- 정우성 (id=6) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('우측 하퇴부 골절', '경골 골절', '깁스 고정, 진통제', DATEADD('DAY', -2, CURRENT_DATE), '박의사', 120000, 6);

-- 한지민 (id=7) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('우하복부 통증', '급성 맹장염', '맹장 절제 수술', DATEADD('DAY', -10, CURRENT_DATE), '김의사', 350000, 7);

-- 오세훈 (id=8) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('속쓰림, 구역질', '만성 위염', '오메프라졸, 소화제', DATEADD('DAY', -5, CURRENT_DATE), '이의사', 20000, 8);

-- 윤아름 (id=9) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('요추 통증, 하지 방사통', '요추 추간판 탈출증', '물리치료, 소염진통제', DATEADD('DAY', -7, CURRENT_DATE), '박의사', 55000, 9);
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('통증 호전', '경과 양호', '재활 운동 처방', DATEADD('DAY', -2, CURRENT_DATE), '박의사', 30000, 9);

-- 강동원 (id=10) 진료 기록
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('흉통, 호흡곤란', '급성 심근경색', '스텐트 시술, 항혈전제', DATEADD('DAY', -14, CURRENT_DATE), '이의사', 1500000, 10);
INSERT INTO CHART (SYMPTOM, DIAGNOSIS, PRESCRIPTION, CHART_DATE, DOCTOR_NAME, FEE, PATIENT_ID) VALUES ('경과 안정', '심근경색 회복기', '아스피린, 베타차단제', DATEADD('DAY', -5, CURRENT_DATE), '이의사', 45000, 10);